apiVersion: v1
kind: Pod
metadata:
  name: alice
spec:
  containers:
  - args:
    - slim-bindings-p2p
    - --local
    - org/ns/alice
    - --shared-secret
    - secret1234secret1234secret123412
    - --slim
    - "http://slim.slim.svc.cluster.local:46357"
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: agntcy/slim/bindings-examples:latest
    imagePullPolicy: IfNotPresent
    name: alice
  serviceAccount: default
  serviceAccountName: default