apiVersion: v1
kind: Pod
metadata:
  name: bob
spec:
  containers:
  - args:
    - slim-bindings-p2p
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --shared-secret
    - secret1234secret1234secret123412
    - --slim
    - "http://slim.slim.svc.cluster.local:46357"
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: agntcy/slim/bindings-examples:latest
    imagePullPolicy: IfNotPresent
    name: bob
    resources: {}
  serviceAccount: default
  serviceAccountName: default
  restartPolicy: OnFailure