apiVersion: v1
kind: ConfigMap
metadata:
  name: slim-with-spire-client-config
  labels:
    app.kubernetes.io/name: slim-client
data:
  client.json: |
    {
      "endpoint": "https://slim.slim.svc.cluster.local:46357",
      "tls": {
        "source": {
          "type": "spire",
          "socket_path": "unix:/tmp/spire-agent/public/api.sock"
        },
        "ca_source": {
          "type": "spire",
          "socket_path": "unix:/tmp/spire-agent/public/api.sock",
          "trust_domains": ["cluster-b.example"]
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  className: spire-spire
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - bob
  workloadSelectorTemplates:
    - k8s:sa:bob
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/default/sa/bob"
  federatesWith:
    - cluster-a.example
---
apiVersion: v1
kind: Pod
metadata:
  name: bob
  labels:
    app.kubernetes.io/name: slim-client
    app.kubernetes.io/component: bob     
spec:
  serviceAccountName: bob
  containers:         
  - args:
    - slim-bindings-p2p
    - --message
    - hello
    - --iterations
    - "10"
    - --local
    - org/ns/bob
    - --remote
    - org/ns/alice
    - --spire-socket-path
    - unix:/tmp/spire-agent/public/api.sock
    - --spire-jwt-audience
    - slim-demo
    - --enable-mls
    - --slim-config
    - /etc/slim/client.json
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    image: agntcy/slim/bindings-examples:latest
    imagePullPolicy: IfNotPresent
    name: client
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /tmp/spire-agent/public/
      readOnly: true
    - name: slim-client-config
      mountPath: /etc/slim
      readOnly: true      
  restartPolicy: OnFailure
  serviceAccountName: bob
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
  - name: slim-client-config
    configMap:
      name: slim-with-spire-client-config
      defaultMode: 0444    
