// Code generated by protoc-gen-slimrpc-java. DO NOT EDIT.
// source: example.proto

package com.exampleservice;

import io.agntcy.slim.bindings.BidiStreamHandler;
import io.agntcy.slim.bindings.Channel;
import io.agntcy.slim.bindings.Context;
import io.agntcy.slim.bindings.RequestStream;
import io.agntcy.slim.bindings.RequestStreamWriter;
import io.agntcy.slim.bindings.ResponseSink;
import io.agntcy.slim.bindings.ResponseStreamReader;
import io.agntcy.slim.bindings.RpcCode;
import io.agntcy.slim.bindings.RpcException;
import io.agntcy.slim.bindings.Server;
import io.agntcy.slim.bindings.UnaryStreamHandler;
import io.agntcy.slim.bindings.UnaryUnaryHandler;
import io.agntcy.slim.bindings.StreamUnaryHandler;
import io.agntcy.slim.bindings.StreamStreamHandler;
import io.agntcy.slim.bindings.slimrpc.ClientRequestStream;
import io.agntcy.slim.bindings.slimrpc.ClientBidiStream;

import static io.agntcy.slim.bindings.slimrpc.SlimrpcUtil.parse;
import static io.agntcy.slim.bindings.slimrpc.SlimrpcUtil.toRpcException;

import java.time.Duration;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public final class TestSlimrpc {
    private TestSlimrpc() {}

    public static final String SERVICE_NAME = "exampleservice.Test";

    public interface TestClient {
        ExampleResponse ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException;
        ResponseStreamReader ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException;
        ClientRequestStream<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata) throws RpcException;
        ClientBidiStream<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata) throws RpcException;

    }

    public static final class TestClientImpl implements TestClient {
        private final Channel channel;

        public TestClientImpl(Channel channel) {
            this.channel = channel;
        }

        @Override
        public ExampleResponse ExampleUnaryUnary(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException {
            byte[] bytes = channel.callUnaryAsync(
                SERVICE_NAME,
                "ExampleUnaryUnary",
                request.toByteArray(),
                timeout,
                metadata
            ).join();
            return parse(bytes, ExampleResponse.parser());
        }

        @Override
        public ResponseStreamReader ExampleUnaryStream(ExampleRequest request, Duration timeout, Map<String, String> metadata) throws RpcException {
            return channel.callUnaryStreamAsync(
                SERVICE_NAME,
                "ExampleUnaryStream",
                request.toByteArray(),
                timeout,
                metadata
            ).join();
        }

        @Override
        public ClientRequestStream<ExampleRequest, ExampleResponse> ExampleStreamUnary(Duration timeout, Map<String, String> metadata) throws RpcException {
            RequestStreamWriter writer = channel.callStreamUnary(
                    SERVICE_NAME,
                    "ExampleStreamUnary",
                    timeout,
                    metadata
            );
            return new ClientRequestStream<>(writer, ExampleRequest::toByteArray, bytes -> parse(bytes, ExampleResponse.parser()));
        }

        @Override
        public ClientBidiStream<ExampleRequest> ExampleStreamStream(Duration timeout, Map<String, String> metadata) throws RpcException {
            BidiStreamHandler handler = channel.callStreamStream(
                    SERVICE_NAME,
                    "ExampleStreamStream",
                    timeout,
                    metadata
            );
            return new ClientBidiStream<>(handler, ExampleRequest::toByteArray);
        }


    }

    public interface TestServer {
        CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Context context);
        CompletableFuture<Void> ExampleUnaryStream(ExampleRequest request, Context context, ResponseSink sink);
        CompletableFuture<ExampleResponse> ExampleStreamUnary(RequestStream stream, Context context);
        CompletableFuture<Void> ExampleStreamStream(RequestStream stream, Context context, ResponseSink sink);

    }

    public abstract static class UnimplementedTestServer implements TestServer {
        @Override
        public CompletableFuture<ExampleResponse> ExampleUnaryUnary(ExampleRequest request, Context context) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleUnaryUnary not implemented"));
        }

        @Override
        public CompletableFuture<Void> ExampleUnaryStream(ExampleRequest request, Context context, ResponseSink sink) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleUnaryStream not implemented"));
        }

        @Override
        public CompletableFuture<ExampleResponse> ExampleStreamUnary(RequestStream stream, Context context) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleStreamUnary not implemented"));
        }

        @Override
        public CompletableFuture<Void> ExampleStreamStream(RequestStream stream, Context context, ResponseSink sink) {
            return CompletableFuture.failedFuture(new UnsupportedOperationException("Method ExampleStreamStream not implemented"));
        }


    }

    public static void registerTestServer(Server server, TestServer impl) {
        server.registerUnaryUnary(SERVICE_NAME, "ExampleUnaryUnary", new Test_ExampleUnaryUnary_Handler(impl));
        server.registerUnaryStream(SERVICE_NAME, "ExampleUnaryStream", new Test_ExampleUnaryStream_Handler(impl));
        server.registerStreamUnary(SERVICE_NAME, "ExampleStreamUnary", new Test_ExampleStreamUnary_Handler(impl));
        server.registerStreamStream(SERVICE_NAME, "ExampleStreamStream", new Test_ExampleStreamStream_Handler(impl));
    }

    private static final class Test_ExampleUnaryUnary_Handler implements UnaryUnaryHandler {
        private final TestServer impl;

        private Test_ExampleUnaryUnary_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<byte[]> handle(byte[] request, Context context) {
            try {
                ExampleRequest parsed = parse(request, ExampleRequest.parser());
                return impl.ExampleUnaryUnary(parsed, context)
                        .thenApply(resp -> resp.toByteArray());
            } catch (Exception e) {
                return CompletableFuture.failedFuture(e);
            }
        }
    }

    private static final class Test_ExampleUnaryStream_Handler implements UnaryStreamHandler {
        private final TestServer impl;

        private Test_ExampleUnaryStream_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<Void> handle(byte[] request, Context context, ResponseSink sink) {
            try {
                ExampleRequest parsed = parse(request, ExampleRequest.parser());
                return impl.ExampleUnaryStream(parsed, context, sink)
                        .handle((ignored, error) -> {
                            if (error != null) {
                                RpcException rpcErr = toRpcException(error, RpcCode.INTERNAL);
                                return (java.util.concurrent.CompletionStage<Void>) sink.sendErrorAsync(rpcErr)
                                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
                            }
                            return (java.util.concurrent.CompletionStage<Void>) sink.closeAsync();
                        })
                        .thenCompose((java.util.concurrent.CompletionStage<Void> stage) -> stage);
            } catch (Exception e) {
                RpcException rpcErr = new RpcException.Rpc(
                        RpcCode.INVALID_ARGUMENT,
                        e.getMessage() == null ? "invalid request" : e.getMessage(),
                        null
                );
                return sink.sendErrorAsync(rpcErr)
                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
            }
        }
    }

    private static final class Test_ExampleStreamUnary_Handler implements StreamUnaryHandler {
        private final TestServer impl;

        private Test_ExampleStreamUnary_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<byte[]> handle(RequestStream stream, Context context) {
            return impl.ExampleStreamUnary(stream, context)
                    .handle((resp, error) -> {
                        if (error != null) {
                            return (java.util.concurrent.CompletionStage<byte[]>) CompletableFuture.<byte[]>failedFuture(
                                toRpcException(error, RpcCode.INTERNAL)
                            );
                        }
                        return (java.util.concurrent.CompletionStage<byte[]>) CompletableFuture.completedFuture(
                                resp.toByteArray()
                        );
                    })
                    .thenCompose((java.util.concurrent.CompletionStage<byte[]> stage) -> stage);
        }
    }

    private static final class Test_ExampleStreamStream_Handler implements StreamStreamHandler {
        private final TestServer impl;

        private Test_ExampleStreamStream_Handler(TestServer impl) {
            this.impl = impl;
        }

        @Override
        public CompletableFuture<Void> handle(RequestStream stream, Context context, ResponseSink sink) {
            return impl.ExampleStreamStream(stream, context, sink)
                    .handle((ignored, error) -> {
                        if (error != null) {
                            RpcException rpcErr = toRpcException(error, RpcCode.INTERNAL);
                            return (java.util.concurrent.CompletionStage<Void>) sink.sendErrorAsync(rpcErr)
                                    .thenCompose(v -> CompletableFuture.<Void>failedFuture(rpcErr));
                        }
                        return (java.util.concurrent.CompletionStage<Void>) sink.closeAsync();
                    })
                    .thenCompose((java.util.concurrent.CompletionStage<Void> stage) -> stage);
        }
    }


}

