// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example.proto
// Protobuf Java Version: 4.29.3

package com.exampleservice;

public interface ExampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exampleservice.ExampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string example_string = 1 [json_name = "exampleString"];</code>
   * @return The exampleString.
   */
  java.lang.String getExampleString();
  /**
   * <code>string example_string = 1 [json_name = "exampleString"];</code>
   * @return The bytes for exampleString.
   */
  com.google.protobuf.ByteString
      getExampleStringBytes();

  /**
   * <code>int64 example_integer = 2 [json_name = "exampleInteger"];</code>
   * @return The exampleInteger.
   */
  long getExampleInteger();
}
