// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example.proto
// Protobuf Java Version: 4.29.3

package com.exampleservice;

/**
 * Protobuf type {@code exampleservice.ExampleResponse}
 */
public final class ExampleResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exampleservice.ExampleResponse)
    ExampleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExampleResponse.class.getName());
  }
  // Use ExampleResponse.newBuilder() to construct.
  private ExampleResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExampleResponse() {
    exampleString_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exampleservice.ExampleProto.internal_static_exampleservice_ExampleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exampleservice.ExampleProto.internal_static_exampleservice_ExampleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exampleservice.ExampleResponse.class, com.exampleservice.ExampleResponse.Builder.class);
  }

  public static final int EXAMPLE_STRING_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object exampleString_ = "";
  /**
   * <code>string example_string = 1 [json_name = "exampleString"];</code>
   * @return The exampleString.
   */
  @java.lang.Override
  public java.lang.String getExampleString() {
    java.lang.Object ref = exampleString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exampleString_ = s;
      return s;
    }
  }
  /**
   * <code>string example_string = 1 [json_name = "exampleString"];</code>
   * @return The bytes for exampleString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExampleStringBytes() {
    java.lang.Object ref = exampleString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exampleString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXAMPLE_INTEGER_FIELD_NUMBER = 2;
  private long exampleInteger_ = 0L;
  /**
   * <code>int64 example_integer = 2 [json_name = "exampleInteger"];</code>
   * @return The exampleInteger.
   */
  @java.lang.Override
  public long getExampleInteger() {
    return exampleInteger_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(exampleString_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, exampleString_);
    }
    if (exampleInteger_ != 0L) {
      output.writeInt64(2, exampleInteger_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(exampleString_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, exampleString_);
    }
    if (exampleInteger_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, exampleInteger_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exampleservice.ExampleResponse)) {
      return super.equals(obj);
    }
    com.exampleservice.ExampleResponse other = (com.exampleservice.ExampleResponse) obj;

    if (!getExampleString()
        .equals(other.getExampleString())) return false;
    if (getExampleInteger()
        != other.getExampleInteger()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXAMPLE_STRING_FIELD_NUMBER;
    hash = (53 * hash) + getExampleString().hashCode();
    hash = (37 * hash) + EXAMPLE_INTEGER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExampleInteger());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exampleservice.ExampleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exampleservice.ExampleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exampleservice.ExampleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.exampleservice.ExampleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.exampleservice.ExampleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.exampleservice.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exampleservice.ExampleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exampleservice.ExampleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exampleservice.ExampleResponse)
      com.exampleservice.ExampleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exampleservice.ExampleProto.internal_static_exampleservice_ExampleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exampleservice.ExampleProto.internal_static_exampleservice_ExampleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exampleservice.ExampleResponse.class, com.exampleservice.ExampleResponse.Builder.class);
    }

    // Construct using com.exampleservice.ExampleResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      exampleString_ = "";
      exampleInteger_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exampleservice.ExampleProto.internal_static_exampleservice_ExampleResponse_descriptor;
    }

    @java.lang.Override
    public com.exampleservice.ExampleResponse getDefaultInstanceForType() {
      return com.exampleservice.ExampleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.exampleservice.ExampleResponse build() {
      com.exampleservice.ExampleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exampleservice.ExampleResponse buildPartial() {
      com.exampleservice.ExampleResponse result = new com.exampleservice.ExampleResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.exampleservice.ExampleResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.exampleString_ = exampleString_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.exampleInteger_ = exampleInteger_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exampleservice.ExampleResponse) {
        return mergeFrom((com.exampleservice.ExampleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exampleservice.ExampleResponse other) {
      if (other == com.exampleservice.ExampleResponse.getDefaultInstance()) return this;
      if (!other.getExampleString().isEmpty()) {
        exampleString_ = other.exampleString_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getExampleInteger() != 0L) {
        setExampleInteger(other.getExampleInteger());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              exampleString_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              exampleInteger_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object exampleString_ = "";
    /**
     * <code>string example_string = 1 [json_name = "exampleString"];</code>
     * @return The exampleString.
     */
    public java.lang.String getExampleString() {
      java.lang.Object ref = exampleString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exampleString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string example_string = 1 [json_name = "exampleString"];</code>
     * @return The bytes for exampleString.
     */
    public com.google.protobuf.ByteString
        getExampleStringBytes() {
      java.lang.Object ref = exampleString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exampleString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string example_string = 1 [json_name = "exampleString"];</code>
     * @param value The exampleString to set.
     * @return This builder for chaining.
     */
    public Builder setExampleString(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      exampleString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string example_string = 1 [json_name = "exampleString"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExampleString() {
      exampleString_ = getDefaultInstance().getExampleString();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string example_string = 1 [json_name = "exampleString"];</code>
     * @param value The bytes for exampleString to set.
     * @return This builder for chaining.
     */
    public Builder setExampleStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      exampleString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long exampleInteger_ ;
    /**
     * <code>int64 example_integer = 2 [json_name = "exampleInteger"];</code>
     * @return The exampleInteger.
     */
    @java.lang.Override
    public long getExampleInteger() {
      return exampleInteger_;
    }
    /**
     * <code>int64 example_integer = 2 [json_name = "exampleInteger"];</code>
     * @param value The exampleInteger to set.
     * @return This builder for chaining.
     */
    public Builder setExampleInteger(long value) {

      exampleInteger_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 example_integer = 2 [json_name = "exampleInteger"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExampleInteger() {
      bitField0_ = (bitField0_ & ~0x00000002);
      exampleInteger_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:exampleservice.ExampleResponse)
  }

  // @@protoc_insertion_point(class_scope:exampleservice.ExampleResponse)
  private static final com.exampleservice.ExampleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exampleservice.ExampleResponse();
  }

  public static com.exampleservice.ExampleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExampleResponse>() {
    @java.lang.Override
    public ExampleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExampleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExampleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exampleservice.ExampleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

